language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
matrix:
  include:
    - python: 3.8
      dist: xenial
      sudo: true
install:
  - pip install -r requirements/test.txt
script:
  - py.test --cov-report term-missing --cov cron_validator test
after_success: coveralls
